### ISSUE TITLE
[ERROR] this._data[0].value = value; TypeError: Cannot create property 'value' on string 'Y'

### ISSUE THREAD

**Issue by chenkenkone** [panates/hl7v2#36]
I got this error. Whenever I tried to fix, always lead me to another issue. I need some help, please.

**/mnt/Kingcolon/server/node_modules/hl7v2/lib/HL7Field.js:122
    this._data[0].value = value;
                        ^

TypeError: Cannot create property 'value' on string 'Y'
    at HL7Field.set value [as value] (/mnt/Kingcolon/server/node_modules/hl7v2/lib/HL7Field.js:122:25)
    at /mnt/Kingcolon/server/node_modules/hl7v2/lib/exchange/HL7Client.js:243:40
    at new Promise (<anonymous>)
    at HL7Client.send (/mnt/Kingcolon/server/node_modules/hl7v2/lib/exchange/HL7Client.js:230:12)
    at /mnt/Kingcolon/server/controllers/nhi.js:1027:28**

> at /mnt/Kingcolon/server/controllers/nhi.js:1027:28 
refters to 
`
.then(() => client.send(msg);
`

 ```javascript
    const testHL7 = async(body) => {
    const DEFAULT_VERSION = "2.5";
    const msg = new HL7Message({version: DEFAULT_VERSION});

    let segMSH = msg.add("MSH");
    segMSH._fields[1]._data = "^~\\&";  // Encoding Characters
    segMSH._fields[2]._data = "EVAS";  // Sending Application
    segMSH._fields[3]._data = "KKK";  // Sending Facility
    segMSH._fields[4]._data = "DCM4CHEE";  // Receiving Application
    segMSH._fields[5]._data = "KKK";  // Recieving Facility
    segMSH._fields[6]._data = `${moment2(new Date()).tz("Asia/Taipei").format("YYYYMMDDHHMMSSZ")}^S`;  
    segMSH._fields[8]._data = "OMI^O23^OMI_O23";  // Message Type
    segMSH._fields[9]._data = "YYYMMDD_patient_no_Type";  // Message Control ID  // ??
    segMSH._fields[10]._data = "T";  // Processing ID, T for training, P for production, D for debugging
    segMSH._fields[11]._data = "2.5";  //Version ID
    segMSH._fields[17]._data = "UNICODE UTF-8";
    
    let segPID = msg.add("PID");
    segPID._fields[1]._data = "patient_no_903874";  // Patient ID -> 病例號
    segPID._fields[2]._data = "K223984446";  // Alternate Patient ID - PID -> 存放病例號
    segPID._fields[4]._data = "林美惠";  // Patient Name -> PID.5.2: Given Name
    segPID._fields[6]._data = `${moment2(new Date("1955-01-23")).tz("Asia/Taipei").format("YYYYMMDDZ")}^D`;  
    segPID._fields[7]._data = "F";  // Sex

    let segPV1 = msg.add("PV1");
    segPV1._fields[1]._data = "O";  // Patient Class -> O stands for Outpatient

    let segORC = msg.add("ORC");
    segORC._fields[0]._data = "NW";  // Order Control, NW stands for New order/service
    // segORC._fields[1]._data = `^IHE_OM_OP^1.3.6.1.4.1.12559.11.1.2.2.4.2^ISO`;  // Placer Order Number
    // segORC._fields[2]._data = `^IHE_OM_OP^1.3.6.1.4.1.12559.11.1.2.2.4.2^ISO`;  // Filler Order Number
    segORC._fields[4]._data = "SC";  // Order Status, SC stands for "In process, scheduled"
    segORC._fields[6]._data = `^20221118&D`;  // Quantity/Timing, ORC.7.4: Start Date/Time

    let segOBR = msg.add("OBR");
    segOBR._fields[1]._data = `^IHE_OM_OP^1.3.6.1.4.1.12559.11.1.2.2.4.2^ISO`;  // Placer Order Number
    // segOBR._fields[2]._data = `^IHE_OM_OP^1.3.6.1.4.1.12559.11.1.2.2.4.2^ISO`;  // Filler Order Number
    segOBR._fields[3]._data = `28017C^coloscopy^Taiwan NHI^2^腸鏡`;  // Universal Service Identifier 
    segOBR._fields[15]._data = `C133225490^doctor name`;  // Ordering Provider 
    segOBR._fields[44]._data = `28017C^coloscopy^Taiwan NHI^2^腸鏡`;  // Procedure Code 

    let segIPC = msg.add("IPC");
    segIPC._fields[4]._data = "ES";  // Modality

    // connection
    const client = new HL7Client();
    client.setKeepAlive(true);
    client.connect(2575, "192.168.0.114")
        .then(() => client.send(msg)
    );

    return;
}
```

**Comment by erayhanoglu** [comment]
_field is protected and you should never use it directly like the line below.
segMSH._fields[2]._data = "EVAS";  // Sending Application

Instead you should use like that
`
let segMSH = msg.add("MSH");
segMSH[2].value = "EVAS";  // Sending Application
`

You may check code examples in the tests.
https://github.com/panates/hl7v2/blob/master/test/04_serialize.js

**Comment by chenkenkone** [comment]
Thank you for answering my question in a very short time. I do appreciate!
